# ServiceAccount for backend
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: default

---

# Role to allow exec into pods
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-exec-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create"]

---

# RoleBinding to bind the role to backend service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-exec-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend-exec-role
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: default
