apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-manager-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-manager-role
rules:
  - apiGroups: [""]
    resources: ["pods","services"]
    verbs: ["create", "delete", "get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-manager-role
subjects:
  - kind: ServiceAccount
    name: pod-manager-sa
    namespace: default
