apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 3000        # Service port
      targetPort: 3000  # Pod containerPort
      nodePort: 30000   # Port exposed on the node (can be 30000–32767)
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 8080        # Service port
      targetPort: 8080  # Pod containerPort
      nodePort: 30001   # Port exposed on the node (can be 30000–32767)
---
apiVersion: v1
kind : Service
metadata:
  name: pod-manager-service
spec:
  selector:
    app: pod-manager
  ports:
    - port: 8080        # Service port
      targetPort: 8080  # Pod containerPort
