apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-service-cleaner
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["watch", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-service-cleaner-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: pod-service-cleaner
  apiGroup: rbac.authorization.k8s.io
