apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-service-watcher
  namespace: default
  labels:
    app: pod-service-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-service-watcher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0  # Ensures no extra pods are spun up
  template:
    metadata:
      labels:
        app: pod-service-watcher
    spec:
      serviceAccountName: default
      containers:
        - name: watcher
          image: watcher:v1
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
